name: Package Release

on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: npm test
        run: |
          npm ci
          npm test
        env:
          CI: true

      - name: npm auth & publish
        run: npm run build && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}
